version: '3'
services:
  vault:
    image: vault:1.3.0
    ports:
      - 8300:8300
    environment:
      - VAULT_LOG=debug
      - SKIP_SETCAP=true
      - VAULT_DEV_ROOT_TOKEN_ID=hunter2
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8300
  targetVault:
    image: vault:1.3.0
    ports:
      - 8400:8400
    environment:
      - VAULT_LOG=debug
      - SKIP_SETCAP=true
      - VAULT_DEV_ROOT_TOKEN_ID=targethunter2
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8400
