version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.1
      - image: vault:0.10.1
        environment:
          SKIP_SETCAP: true
          VAULT_DEV_ROOT_TOKEN_ID: hunter2
          VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8300
    parallelism: 4
    working_directory: /go/src/github.com/Lingrino/vaku
    steps:
      - checkout
      - run:
          name: Make sure there's nothing to go fmt
          command: test -z $(gofmt -l -w -s vaku/)
      - run:
          name: Install dep
          command: go get -u github.com/golang/dep/cmd/dep
      - run:
          name: Make sure there's no packages to update
          command: test -z $(dep ensure -update -dry-run)
      - run:
          name: Get Packages
          command: dep ensure
      - run:
          name: Run Tests
          command: go test -cover -v ./...
  deploy:
    docker:
      - image: circleci/golang:1.10.1
    working_directory: /go/src/github.com/Lingrino/vaku
    steps:
      - checkout
      - run:
          name: Install dep
          command: go get -u github.com/golang/dep/cmd/dep
      - run:
          name: Get Packages
          command: dep ensure
      - run:
          name: Build and deploy a new version
          command: curl -sL https://git.io/goreleaser | bash
  deploy-www:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Install awscli
          command: pip install --no-warn-script-location --user awscli
      - run:
          name: Upload the new site to S3
          command: /home/circleci/.local/bin/aws --region us-east-2 s3 sync www/ s3://vaku.io-20180604033539915400000001
      - run:
          name: Invalidate the cloudfront cache
          command: /home/circleci/.local/bin/aws cloudfront create-invalidation --distribution-id E2F9NPK13ZLB4G --paths "/*"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
      - deploy-www:
          filters:
            branches:
              only: master
