version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
      - image: vault:latest
        name: vault-test
        environment:
          VAULT_DEV_ROOT_TOKEN_ID: hunter2
          VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    working_directory: /go/src/github.com/lingrino/vault-kv-utils
    environment:
      - VAULT_ADDR: http://localhost:8200
      - VAULT_TOKEN: hunter2
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
