version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.1
      - image: vault:0.10.1
        environment:
          SKIP_SETCAP: true
          VAULT_DEV_ROOT_TOKEN_ID: hunter2
          VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8300
    environment:
      - VAULT_ADDR: http://0.0.0.0:8300
      - VAULT_TOKEN: hunter2
    parallelism: 4
    working_directory: /go/src/github.com/lingrino/vaku
    steps:
      - checkout
      - run:
          name: Make sure there's nothing to go fmt
          command: test -z $(go fmt ./...)
      - run:
          name: Install dep
          command: go get -u github.com/golang/dep/cmd/dep
      - run:
          name: Get Packages
          command: dep ensure
      - run:
          name: Run Tests
          command: go test -cover -v ./...
