name: Repo - Validate

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: License Exists
        run: test -f LICENSE
      - name: Gitignore Exists
        run: test -f .gitignore
      - name: Readme Exists
        run: test -f README.md
      - name: Readme Lint
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: ./README.md
          config: ./.markdownlint.json
